### ISSUE TITLE
Why is n=1 not allowed?

### ISSUE THREAD

**Issue by MatthieuStigler** [hsbadr/HiClimR#4]
Hi

Thanks for the package! I was checking it as i wanted to do contiguity-constrained clustering, comparing it with R packages `constr.hclust` and `ClustGeo`. 

I tried to do a univariate analysis, but this does not seem to be allowed? From which step does this constraint come from, as `HiClimR` has a lot of different steps involved? I just changed the code internally, changing from stop to warning, and was still able to obtain some output, so I guess the constraint is not at the programming level?

Also, have you considered providing a low-level function doing only the contiguity-constrained clustering step? Personally I would only want this step in my analysis, and a lighter version would be very appreciated!

Thanks!

**Comment by hsbadr** [comment]
Hi,

I need more info to answer your question, as instructed [here](https://cran.r-project.org/web/packages/HiClimR/vignettes/BugReports.html).

How do you call `HiClimR` and what do you mean by `n`? The objective of package is to do regionalization, specifically for hydroclimateology, but it can be applied to any correlation-based clustering. Both univariate and multivariate clustering are supported (i.e., the number of variables can be equal to or greater than one). So, if you mean by `n` the number of regions, it doesn't make sense to apply clustering at all since you request all data to be grouped in one cluster.

**Comment by MatthieuStigler** [comment]
Hi

Sorry if that wasn't very clear. I should have made it more clear that my question is linked to Pull request #3 . 

After the pull request, trying to cluster on a single variable gives error message: `must have n ≥ 2 objects to cluster`. Indeed I am not sure exactly what you call `n` here, _object_? Is that the number of _dimensions/year_ of the first variable? Why does the object/dimension need to be >1? Is that because of the specific regionalization algorithm, or some other algorithms in the `HiClimR` function? (hence the question whether the regionalization function could be also provided as a stand-alone function?).

Thanks!

See what I am trying to do:

``` r
library(HiClimR)

x <- TestCase$x
lon <- TestCase$lon
lat <- TestCase$lat

y <- HiClimR(x[,1,drop=FALSE], lon = lon, lat = lat, plot=FALSE, verbose=FALSE)
#> Error in HiClimR(x[, 1, drop = FALSE], lon = lon, lat = lat, plot = FALSE, : must have n ≥ 2 objects to cluster

packageVersion("HiClimR") # after pull request #3!!
#> [1] '2.1.5'
sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 19.10
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] HiClimR_2.1.5
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3        digest_0.6.24     reprex_0.3.0.9001 magrittr_1.5     
#>  [5] evaluate_0.14     ncdf4_1.17        highr_0.8         rlang_0.4.4      
#>  [9] stringi_1.4.6     fs_1.3.1          rmarkdown_2.1     tools_3.6.2      
#> [13] stringr_1.4.0     xfun_0.12         yaml_2.2.0        compiler_3.6.2   
#> [17] htmltools_0.4.0   knitr_1.28
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hsbadr** [comment]
I see. The problem here comes from the dissimilarity measure in `HiClimR`. It uses correlation distance which doesn't support scalars. The dimensions of your input matrix (`x[,1,drop=FALSE]`) has only one column/observation which is not enough to compute the dissimilarities (or correlations) between the rows. You need to provide 2 or more columns in the input matrix.

**Comment by MatthieuStigler** [comment]
Oh ok. I am curious why you chose a correlation distance rather than euclidean? re there papers claiming these should be prefferred? But I thought they were actually very closely related?

Thanks!

**Comment by hsbadr** [comment]
The correlation distance is preferred for hydroclimate regionalization at different temporal scales (the main objective of the package), and maybe other applications such as gene selection and classification. Moreover, the `regional` linkage method introduced in `HiClimR` paper is based on the correlation distance.
